name: ebook
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_udid: ^3.0.0

  cupertino_icons: ^1.0.6

  base_core:
    path: plugins/base_core
  base_https:
    path: plugins/base_https

  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.3.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Italic
      fonts:
        - asset: assets/fonts/GoogleSansItalic.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/GoogleSansRegular.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/GoogleSansBold.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/GoogleSansMedium.ttf
    - family: GoogleSansThin
      fonts:
        - asset: assets/fonts/GoogleSansThin.ttf

  assets:
    - plugins/base_https/.env
    - plugins/base_https/.stag.env
    - plugins/base_https/.prod.env
    - plugins/base_core/assets_base/bases/
    - books/chantroisangtao/
    - books/chantroisangtao/9/
    - books/chantroisangtao/9/20/
    - books/chantroisangtao/9/18/
    - books/chantroisangtao/9/9/
    - books/chantroisangtao/9/0/
    - books/chantroisangtao/9/11/
    - books/chantroisangtao/9/7/
    - books/chantroisangtao/9/16/
    - books/chantroisangtao/9/6/
    - books/chantroisangtao/9/17/
    - books/chantroisangtao/9/1/
    - books/chantroisangtao/9/10/
    - books/chantroisangtao/9/19/
    - books/chantroisangtao/9/8/
    - books/chantroisangtao/9/21/
    - books/chantroisangtao/9/4/
    - books/chantroisangtao/9/15/
    - books/chantroisangtao/9/3/
    - books/chantroisangtao/9/12/
    - books/chantroisangtao/9/2/
    - books/chantroisangtao/9/13/
    - books/chantroisangtao/9/5/
    - books/chantroisangtao/9/14/
    - books/chantroisangtao/0/
    - books/chantroisangtao/0/0/
    - books/chantroisangtao/0/7/
    - books/chantroisangtao/0/6/
    - books/chantroisangtao/0/1/
    - books/chantroisangtao/0/8/
    - books/chantroisangtao/0/4/
    - books/chantroisangtao/0/3/
    - books/chantroisangtao/0/2/
    - books/chantroisangtao/0/5/
    - books/chantroisangtao/11/
    - books/chantroisangtao/11/9/
    - books/chantroisangtao/11/0/
    - books/chantroisangtao/11/11/
    - books/chantroisangtao/11/7/
    - books/chantroisangtao/11/6/
    - books/chantroisangtao/11/1/
    - books/chantroisangtao/11/10/
    - books/chantroisangtao/11/8/
    - books/chantroisangtao/11/4/
    - books/chantroisangtao/11/3/
    - books/chantroisangtao/11/12/
    - books/chantroisangtao/11/2/
    - books/chantroisangtao/11/13/
    - books/chantroisangtao/11/5/
    - books/chantroisangtao/11/14/
    - books/chantroisangtao/7/
    - books/chantroisangtao/7/9/
    - books/chantroisangtao/7/0/
    - books/chantroisangtao/7/11/
    - books/chantroisangtao/7/7/
    - books/chantroisangtao/7/6/
    - books/chantroisangtao/7/1/
    - books/chantroisangtao/7/10/
    - books/chantroisangtao/7/8/
    - books/chantroisangtao/7/4/
    - books/chantroisangtao/7/15/
    - books/chantroisangtao/7/3/
    - books/chantroisangtao/7/12/
    - books/chantroisangtao/7/2/
    - books/chantroisangtao/7/13/
    - books/chantroisangtao/7/5/
    - books/chantroisangtao/7/14/
    - books/chantroisangtao/6/
    - books/chantroisangtao/6/9/
    - books/chantroisangtao/6/0/
    - books/chantroisangtao/6/11/
    - books/chantroisangtao/6/7/
    - books/chantroisangtao/6/6/
    - books/chantroisangtao/6/1/
    - books/chantroisangtao/6/10/
    - books/chantroisangtao/6/8/
    - books/chantroisangtao/6/4/
    - books/chantroisangtao/6/3/
    - books/chantroisangtao/6/12/
    - books/chantroisangtao/6/2/
    - books/chantroisangtao/6/13/
    - books/chantroisangtao/6/5/
    - books/chantroisangtao/6/14/
    - books/chantroisangtao/1/
    - books/chantroisangtao/1/9/
    - books/chantroisangtao/1/0/
    - books/chantroisangtao/1/7/
    - books/chantroisangtao/1/6/
    - books/chantroisangtao/1/1/
    - books/chantroisangtao/1/8/
    - books/chantroisangtao/1/4/
    - books/chantroisangtao/1/3/
    - books/chantroisangtao/1/2/
    - books/chantroisangtao/1/5/
    - books/chantroisangtao/10/
    - books/chantroisangtao/10/9/
    - books/chantroisangtao/10/0/
    - books/chantroisangtao/10/11/
    - books/chantroisangtao/10/7/
    - books/chantroisangtao/10/16/
    - books/chantroisangtao/10/6/
    - books/chantroisangtao/10/17/
    - books/chantroisangtao/10/1/
    - books/chantroisangtao/10/10/
    - books/chantroisangtao/10/8/
    - books/chantroisangtao/10/4/
    - books/chantroisangtao/10/15/
    - books/chantroisangtao/10/3/
    - books/chantroisangtao/10/12/
    - books/chantroisangtao/10/2/
    - books/chantroisangtao/10/13/
    - books/chantroisangtao/10/5/
    - books/chantroisangtao/10/14/
    - books/chantroisangtao/8/
    - books/chantroisangtao/8/9/
    - books/chantroisangtao/8/0/
    - books/chantroisangtao/8/11/
    - books/chantroisangtao/8/7/
    - books/chantroisangtao/8/6/
    - books/chantroisangtao/8/1/
    - books/chantroisangtao/8/10/
    - books/chantroisangtao/8/8/
    - books/chantroisangtao/8/4/
    - books/chantroisangtao/8/15/
    - books/chantroisangtao/8/3/
    - books/chantroisangtao/8/12/
    - books/chantroisangtao/8/2/
    - books/chantroisangtao/8/13/
    - books/chantroisangtao/8/5/
    - books/chantroisangtao/8/14/
    - books/chantroisangtao/4/
    - books/chantroisangtao/4/9/
    - books/chantroisangtao/4/0/
    - books/chantroisangtao/4/11/
    - books/chantroisangtao/4/7/
    - books/chantroisangtao/4/6/
    - books/chantroisangtao/4/1/
    - books/chantroisangtao/4/10/
    - books/chantroisangtao/4/8/
    - books/chantroisangtao/4/4/
    - books/chantroisangtao/4/3/
    - books/chantroisangtao/4/12/
    - books/chantroisangtao/4/2/
    - books/chantroisangtao/4/13/
    - books/chantroisangtao/4/5/
    - books/chantroisangtao/3/
    - books/chantroisangtao/3/9/
    - books/chantroisangtao/3/0/
    - books/chantroisangtao/3/11/
    - books/chantroisangtao/3/7/
    - books/chantroisangtao/3/6/
    - books/chantroisangtao/3/1/
    - books/chantroisangtao/3/10/
    - books/chantroisangtao/3/8/
    - books/chantroisangtao/3/4/
    - books/chantroisangtao/3/3/
    - books/chantroisangtao/3/12/
    - books/chantroisangtao/3/2/
    - books/chantroisangtao/3/13/
    - books/chantroisangtao/3/5/
    - books/chantroisangtao/3/14/
    - books/chantroisangtao/2/
    - books/chantroisangtao/2/9/
    - books/chantroisangtao/2/0/
    - books/chantroisangtao/2/11/
    - books/chantroisangtao/2/7/
    - books/chantroisangtao/2/6/
    - books/chantroisangtao/2/1/
    - books/chantroisangtao/2/10/
    - books/chantroisangtao/2/8/
    - books/chantroisangtao/2/4/
    - books/chantroisangtao/2/3/
    - books/chantroisangtao/2/12/
    - books/chantroisangtao/2/2/
    - books/chantroisangtao/2/5/
    - books/chantroisangtao/5/
    - books/chantroisangtao/5/9/
    - books/chantroisangtao/5/0/
    - books/chantroisangtao/5/11/
    - books/chantroisangtao/5/7/
    - books/chantroisangtao/5/6/
    - books/chantroisangtao/5/1/
    - books/chantroisangtao/5/10/
    - books/chantroisangtao/5/8/
    - books/chantroisangtao/5/4/
    - books/chantroisangtao/5/3/
    - books/chantroisangtao/5/2/
    - books/chantroisangtao/5/5/
    # assets-generator-begin
    - assets/images/
    - assets/images/settings/
    - assets/images/home/
    - assets/images/app/
    - assets/images/web/
    - assets/images/tabbar/
    - assets/images/parrent/
    - assets/images/parrent/account_manager/
    - assets/images/time/
    - assets/images/dialog/
    - assets/images/common/
    - assets/images/avartar/
    - assets/images/report/
    - assets/images/logo_book/
    - assets/images/avatars/
    - assets/images/login/
    - assets/fonts/
    # assets-generator-end
