name: base_3_19_4_getx_mvvm
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  base_core:
    path: plugins/base_core

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.3.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Italic
      fonts:
        - asset: assets/fonts/GoogleSansItalic.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/GoogleSansRegular.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/GoogleSansBold.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/GoogleSansMedium.ttf
    - family: GoogleSansThin
      fonts:
        - asset: assets/fonts/GoogleSansThin.ttf

  assets:
    # - plugins/base_https/.env
    # - plugins/base_https/.stag.env
    # - plugins/base_https/.prod.env
    # - plugins/base_core/assets_base/bases/
    # assets-generator-begin
    - assets/images/
    - assets/images/settings/
    - assets/images/home/
    - assets/images/app/
    - assets/images/web/
    - assets/images/tabbar/
    - assets/images/parrent/
    - assets/images/parrent/account_manager/
    - assets/images/time/
    - assets/images/dialog/
    - assets/images/common/
    - assets/images/avartar/
    - assets/images/report/
    - assets/images/avatars/
    - assets/images/login/
    - assets/fonts/
    # assets-generator-end
